[project]
name = "backend"
version = "0.1.0"
description = "A FastAPI project using Poetry"
authors = [{ name = "heyimdima", email = "bondardima@icloud.com" }]
readme = "README.md"
requires-python = "3.11.*"
dependencies = ["fastapi (>=0.115.11,<0.116.0)", "uvicorn (>=0.34.0,<0.35.0)", "crawl4ai (==0.4.248)", "python-dotenv (>=1.0.1,<2.0.0)", "beautifulsoup4 (>=4.13.3,<5.0.0)", "pinecone (>=6.0.2,<7.0.0)", "html-to-markdown (>=1.2.0,<2.0.0)", "langchain-text-splitters (>=0.3.6,<0.4.0)", "supabase (>=2.13.0,<3.0.0)", "markdownify (>=1.1.0,<2.0.0)"]

[tool.poetry]
packages = [{ include = "backend", from = "src" }]


[tool.poetry.group.dev.dependencies]
ipykernel = "^6.29.5"

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
